### ISSUE TITLE
Change Namespace to FFaker

### ISSUE THREAD

**Issue by nacengineer** [EmmanuelOga/ffaker#114]
## Thanks!!!! :D :D 

First, Thanks for the awesome refactored gem, I use it in all my projects! This IMO is something we don't tell gem maintainers/creators enough, so thanks! :)

**Now to my Issue**

I understand the most likely reason for using the same module namespace as the Faker gem, _Faker::_, is that it simplifies the transition to ffaker. But it should be a different module namespace IMO, as using the same namespace opens the door for namespace collisions. 

Pleading my case...

Modern IDEs allow you to re-factor code fairly easily... i.e. change _Faker::_ to _FFaker::_ should be a fairly simple _Find and Replace_ (case sensitive) search for  _Faker::_)

Example of namespace collision, the **migrant gem** requires the Faker gem... this creates namespace collisions with FFaker. For me it was in the Address module. 

I would argue that the better approach is to not be a swap in replacement for Faker and instead be a true fork with different module namespace, **FFaker** as this will avoid namespace collisions like the one I was dealing with in the migrant gem. While it is possible to change this down as a bug, its really the desired behavior. 

Alternative approach (but a lot more work) 

Make ffaker an extension of the faker gem and "monkey patch" faker's modules. This is IMO less desirable as its a lot more developer work / reorganization of directories etc. You only have a limited time.

**Comment by dannysperry** [comment]
@EmmanuelOga I submitted a PR for this. seemed easy/tedious and I was bored ( #170  )

**Comment by rocknruby** [comment]
I released version 2.0.0 which solves the namespace issue. :clap:
