### ISSUE TITLE
New maintainer needed

### ISSUE THREAD

**Issue by EmmanuelOga** [EmmanuelOga/ffaker#161]
Hey guys,

I feel sorry for the state of this gem but I barely use it for anything anymore and it is hard for me to find time to maintain it. If you would like to step up and take the helm let me know.

Thanks!

P.S.: just to clarify the part I feel sorry about is the number of open issues and pull requests... the codebase itself is pretty clean and shouldn't be hard to mantain :smile:

**Comment by EmmanuelOga** [comment]
@rocknruby jumped to help, thanks so much!

**Comment by PapePathe** [comment]
+1 @rocknruby
