### ISSUE TITLE
New hash syntax breaks Ruby 1.8 implementations from version 1.31.0 to 1.32.0.

### ISSUE THREAD

**Issue by mhuggins** [EmmanuelOga/ffaker#176]
Looks like the release that just came out today breaks implementations that are running on Ruby 1.8 requiring the hash-rocket syntax.  [This commit](https://github.com/EmmanuelOga/ffaker/commit/cb2dae5a7977ab9a65edf9ede0cc4450bd501687) appears to be the culprit.  See [this PR comment](https://github.com/airblade/paper_trail/pull/476#issuecomment-72889606) for details on where this is used -- note that the paper_trail gem supports old ruby versions while using the ffaker gem.

**Comment by rocknruby** [comment]
Hi @mhuggins, we stopped the support for ruby 1.8.7, as you can see in the PR #155.

**Comment by mhuggins** [comment]
Thanks for letting me know this is intentional.  Sounds like the paper_trail gem is either going to stop support as well, or at least use an earlier version of ffaker in the interim.

**Comment by batter** [comment]
@rocknruby - If you've dropped support for Ruby18 then I believe it is advisable to add a [`required_ruby_version`](http://guides.rubygems.org/specification-reference/#required_ruby_version=) of `1.9.2` to the gemspec. Happy to make a PR if that is helpful.

**Comment by rocknruby** [comment]
Hi @batter , thanks for your advice. I've set the minimum required ruby versión and released a new versión for ffaker. :+1:
