### ISSUE TITLE
Invalid canadian postal codes

### ISSUE THREAD

**Issue by aarana-ix** [EmmanuelOga/ffaker#178]
The logic used to generate canadian zipcodes is wrong. The current format mask is this: `'?#? #?#'`. However, not all letters are valid in all the positions, so calling `bothify` on that may return invalid postal codes.

Valid canadian postal codes should match this regexp: ` /^[A-CEGHJK-NPR-TVXY][0-9][A-CEGHJK-NPR-TV-Z] [0-9][A-CEGHJK-NPR-TV-Z][0-9]$/`

If you wish, I will fork this repo and implement the necessary changes. I just wanted to open the issue to see if something like this would be merged, and to link the PR back to the issue for discussion.

**Comment by rocknruby** [comment]
Hopefully @steveclarke knows more, he made the first implementation. :+1: 
If the postal code are wrong generated it would be great when you could create a fix-branch and a PR. :gift:

**Comment by marocchino** [comment]
I will take this.
